### ISSUE TITLE
Cannot authenticate with Nexa Bridge X

### ISSUE THREAD

**Issue by olterman** [andersevenrud/ha-nexa-bridge-x#42]
So today I decided to spring for a nexa bridge X just because this integration exists, however I cannot seem to authenticate to get the integration working. When I open a browser I can acess the api with the standard credentials ... but HACS integration will not allow me to authenticate .... 

![Screenshot from 2024-04-10 16-34-02](https://github.com/andersevenrud/ha-nexa-bridge-x/assets/40863714/d458c541-b3e9-496c-8bc2-278ee3375b5a)

**Comment by andersevenrud** [comment]
First thing I would recommend is to check for firmware updates.

---

Are you familiar with tools such as Postman ?

It would really help to see what your Bridge reports from http://192.168.10.206/v1/info (Requires "Digest Authentication" with username `nexa` and password `nexa`).

I have seen some X devices running with legacy firmware which could cause this exact error (#31). This should be fairly easy to fix if that's the case.

**Comment by olterman** [comment]
After I added my first device to the nexa I can no longer access the api with web-browser so I cannot get the report from postman. My Nexa Bridge X is runing firmware 1.7.3 if that helps

**Comment by andersevenrud** [comment]
> After I added my first device to the nexa I can no longer access the api with web-browser so I cannot get the report from postman. 

Huh. That's really strange. I know there can be some intermittent issues with the Bridge API and web interface depending on the firmware version, but usually not for long.

> My Nexa Bridge X is runing firmware 1.7.3 if that helps

That's actually the legacy firmware, which is why this integration failed. It expects the Bride X to run on at least version 2.

---

I might just go ahead and remove this check since there are now multiple reports of this, but installing the latest firmware is my recommendation (if you get things working again).

**Comment by olterman** [comment]
I have been searching and cannot find a way to actually uppgrade firmware
manually. Any tips, links, advice ?

**Comment by andersevenrud** [comment]
I'm actually not sure. When I used the Nexa bridge I think it did it automatically somehow... I actually can't remember.

Have you tried their Android/iOS App ?

**Comment by olterman** [comment]
The Android app does not have an upgrade version (though maybe that is also
because of the firmware diwcrepency) I have emailed Nexa support.

**Comment by andersevenrud** [comment]
I would love to hear about the response on that so I can document it.

I went through all of the links I've gathered about the bridge, including all of the Firmware update stuff and it actually does not at any point mention how to apply them, only news and changelogs.

---

FYI I removed the check and created a new release. You can try setting up the integration without the legacy checkbox, but I have no idea if that will work as expected or not.

Let's just hope support follows through here. Kinda lame if you bought an X and be stuck with the legacy firmware.

**Comment by andersevenrud** [comment]
> but I have no idea if that will work as expected or not.

After looking things up some more it seems that 1.7.3 was some sort of "transition" version of the firmware before 2.x started rolling out and should be compatible enough for this integration to work (without enabling legacy mode).

So the latest integration update *should* work for anyone running this specific version. Hopefully without any issues 🤞

**Comment by olterman** [comment]
With the new update I could add the integration, so partial success! However the integration now tells me: No devices or entities. 

`2024-04-12 07:00:01.740 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/info: null
2024-04-12 07:00:01.914 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/info: 200
2024-04-12 07:00:01.915 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/info: null
2024-04-12 07:00:01.918 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/nodes: null
2024-04-12 07:00:01.921 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/energy: null
2024-04-12 07:00:01.923 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/energy/nodes: null
2024-04-12 07:00:02.166 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/energy: 200
2024-04-12 07:00:02.191 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/nodes: 200
2024-04-12 07:00:02.205 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/energy/nodes: 404
2024-04-12 07:00:02.206 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] Finished fetching Nexa Bridge X Coordinator data in 0.291 seconds (success: False)`

**Comment by olterman** [comment]
after rebooting the nexa I got this;

`2024-04-12 07:05:15.732 DEBUG (MainThread) [custom_components.nexa_bridge_x.nexa] GET http://192.168.10.206/v1/info: null
2024-04-12 07:05:15.740 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Nexa Bridge X for nexa_bridge_x
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
yield
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
resp = await self._pool.handle_async_request(req)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
raise exc from None
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
response = await connection.handle_async_request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
raise exc
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
stream = await self._connect(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
stream = await self._network_backend.connect_tcp(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
return await self._backend.connect_tcp(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 112, in connect_tcp
with map_exceptions(exc_map):
File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
self.gen.throw(value)
File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/nexa_bridge_x/__init__.py", line 34, in async_setup_entry
await platform.init()
File "/config/custom_components/nexa_bridge_x/nexa.py", line 129, in init
await self.api.test_connection()
File "/config/custom_components/nexa_bridge_x/nexa.py", line 308, in test_connection
result = await self.fetch_info()
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/nexa_bridge_x/nexa.py", line 328, in fetch_info
return await self.request("get", "info")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/nexa_bridge_x/nexa.py", line 296, in request
response = await self._client.request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
return await self.send(request, auth=auth, follow_redirects=follow_redirects)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
response = await self._send_handling_auth(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
response = await self._send_handling_redirects(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
response = await self._send_single_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
response = await transport.handle_async_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
with map_httpcore_exceptions():
File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
self.gen.throw(value)
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed`

**Comment by andersevenrud** [comment]
> With the new update I could add the integration, so partial success! However the integration now tells me: No devices or entities.

I see why by the log you provided. I will fix this asap!

**Comment by andersevenrud** [comment]
> I will fix this asap!

I published a new release that hopefully takes care of this issue and makes your device show up.

**Comment by olterman** [comment]
Thank you !! It now works, I can see my entities in HA. I still want to be able to upgrade my bridge, but at least now I can make it work with my automations!

**Comment by andersevenrud** [comment]
Awesome!

Thanks for reporting. I was totally unaware that 1.7.3 actually was broken in this integration, so this is great news for any others that has an outdated firmware as well and wants to try out HA.

**Comment by olterman** [comment]
Hey after a very loooong wait Nexa support updated my firmware and I am now running 2.4, do I need to redo the integration for full functionality or was it just the authentication that needed tweaking for legacy ?

**Comment by andersevenrud** [comment]
How was the process of updating ?

> Hey after a very loooong wait Nexa support updated my firmware and I am now running 2.4, do I need to redo the integration for full functionality or was it just the authentication that needed tweaking for legacy ?

Ideally you should set up the integration again. But if everyting is working, then you can just skip it :)

**Comment by olterman** [comment]
The process was, I woke up to an email saying, sorry it took so long - we are understaffed - we have updated and restarted your unit.

**Comment by andersevenrud** [comment]
Hm, so it was a manual remote operation. That's kind of lame and unnecessary work for the support team 😅

**Comment by olterman** [comment]
I know, completely bonkers. Anyways I deleted the integration and readded, now at least I get states on my powerplugs - YAY! Time to se if it can handle my doorlock :)

**Comment by andersevenrud** [comment]
Nice :)

Then I assume this can be closed again. If you're still running into issues, please open a new issue.
